### ISSUE TITLE
Fails to build with ffmpeg >= 4.4

### ISSUE THREAD

**Issue by jbeich** [VFR-maniac/L-SMASH-Works#80]
Regressed by https://github.com/ffmpeg/ffmpeg/commit/cea7c19cda0ea1630ae1de8c102ab14231b9db10. From [error log](https://github.com/VFR-maniac/L-SMASH-Works/files/6181767/vapoursynth-l-smash-works-0.0.940.log):
```c
../common/lwindex.c:2457:80: error: no member named 'nb_index_entries' in 'struct AVStream'
        if( adhp->dv_in_avi == 1 && format_ctx->streams[ adhp->stream_index ]->nb_index_entries == 0 )
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../common/lwindex.c:2505:60: error: no member named 'index_entries' in 'struct AVStream'
                temp = (AVIndexEntry *)av_realloc( stream->index_entries, allocated_size );
                                                   ~~~~~~  ^
../common/lwindex.c:2521:29: error: no member named 'index_entries' in 'struct AVStream'
                    stream->index_entries                = temp;
                    ~~~~~~  ^
../common/lwindex.c:2522:29: error: no member named 'index_entries_allocated_size' in 'struct AVStream'
                    stream->index_entries_allocated_size = allocated_size;
                    ~~~~~~  ^
../common/lwindex.c:2523:29: error: no member named 'nb_index_entries' in 'struct AVStream'
                    stream->nb_index_entries             = i;
                    ~~~~~~  ^
../common/lwindex.c:2529:60: error: no member named 'index_entries' in 'struct AVStream'
                temp = (AVIndexEntry *)av_realloc( stream->index_entries, allocated_size );
                                                   ~~~~~~  ^
../common/lwindex.c:2546:29: error: no member named 'index_entries' in 'struct AVStream'
                    stream->index_entries                = temp;
                    ~~~~~~  ^
../common/lwindex.c:2547:29: error: no member named 'index_entries_allocated_size' in 'struct AVStream'
                    stream->index_entries_allocated_size = allocated_size;
                    ~~~~~~  ^
../common/lwindex.c:2548:29: error: no member named 'nb_index_entries' in 'struct AVStream'
                    stream->nb_index_entries             = i;
                    ~~~~~~  ^
../common/lwindex.c:2554:36: error: no member named 'index_entries' in 'struct AVStream'
                av_freep( &stream->index_entries );
                           ~~~~~~  ^
../common/lwindex.c:2555:25: error: no member named 'index_entries_allocated_size' in 'struct AVStream'
                stream->index_entries_allocated_size = 0;
                ~~~~~~  ^
../common/lwindex.c:2556:25: error: no member named 'nb_index_entries' in 'struct AVStream'
                stream->nb_index_entries             = 0;
                ~~~~~~  ^
../common/lwindex.c:2565:110: error: no member named 'nb_index_entries' in 'struct AVStream'
            print_index( index, "<StreamIndexEntries=%d,%d,%d>\n", stream_index, AVMEDIA_TYPE_VIDEO, stream->nb_index_entries );
                                                                                                     ~~~~~~  ^
../common/lwindex.c:2567:45: error: no member named 'nb_index_entries' in 'struct AVStream'
                for( int i = 0; i < stream->nb_index_entries; i++ )
                                    ~~~~~~  ^
../common/lwindex.c:2568:59: error: no member named 'index_entries' in 'struct AVStream'
                    write_av_index_entry( index, &stream->index_entries[i] );
                                                  ~~~~~~  ^
../common/lwindex.c:2569:30: error: no member named 'nb_index_entries' in 'struct AVStream'
            else if( stream->nb_index_entries > 0 )
                     ~~~~~~  ^
../common/lwindex.c:2571:74: error: no member named 'index_entries_allocated_size' in 'struct AVStream'
                vdhp->index_entries = (AVIndexEntry *)av_malloc( stream->index_entries_allocated_size );
                                                                 ~~~~~~  ^
../common/lwindex.c:2574:45: error: no member named 'nb_index_entries' in 'struct AVStream'
                for( int i = 0; i < stream->nb_index_entries; i++ )
                                    ~~~~~~  ^
../common/lwindex.c:2576:49: error: no member named 'index_entries' in 'struct AVStream'
                    AVIndexEntry *ie = &stream->index_entries[i];
                                        ~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by jbeich** [comment]
Reverted in https://github.com/FFmpeg/FFmpeg/commit/0be265e9a100adc778c1c3cf52155a6326043b85

See also https://gitlab.freedesktop.org/gstreamer/gst-libav/-/issues/85
